[package]
name = "bevy_grackle"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bevy_mod_picking = "0.17.0"
bevy_quill = { path = "../.." }
bevy_egret = { path = "../bevy_egret" }
static_init = "1.0.3"
